services:
  - type: web
    name: betbrain-api
    env: node
    plan: free
    rootDir: betbrain-server
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SPORTS_KEY
        sync: false
      - key: ODDS_KEY
        sync: false
      - key: BALLDONTLIE_KEY
        sync: false
